name: rotate_service_account_key_cloud_function

on:
  push:
    paths:
      - 'rotate_service_account_key/cloud_function/**'
      - '.github/workflows/**'

jobs:
  super-lint:
    name: Deploy rotate_service_account_key
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3
        with:
          project_id: randstad-etl-poc
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy rotate_service_account_key \
            --gen2 \
            --runtime python310 \
            --region=us-central1 \
            --entry-point main \
            --source rotate_service_account_key/cloud_function \
            --trigger-http \
            --service-account randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com \
            --set-env-vars SA_EMAIL=randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com,SA_NAME=randstad-key-test,secret_id=randstad-secret \
            --allow-unauthenticated

