name: Update-My-Function

on:
  push:
    paths:
      - 'cloud_function/**'

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
#        with:
#          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
#          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'my-function'
          runtime: 'python310'
          entry_point : 'main'
          source_dir : "cloud_function"

      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'


