name: Super-Linter

on:
  push:
    paths:
      - 'cloud_function/**'
      - '.github/workflows/**'

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3
        with:
          project_id: randstad-etl-poc
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy my-function \
            --gen2 \
            --runtime python310 \
            --region=us-central1 \
            --entry-point main \
            --source cloud_function \
            --trigger-http \
            --service-account randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com \
            --set-env-vars SA_EMAIL=randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com,VAR2=value2,VAR3=value3 \
            --allow-unauthenticated

