name: Create Dict

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'


jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read JSON and Create Dictionary
        run: |
          # Read the JSON file into a variable
          json_content=$(cat path/to/your/file.json)
          
          # Parse the JSON content into a dictionary
          dictionary=$(echo "$json_content" | jq -c -r 'to_entries | map({(.key): .value}) | add')
          
          # Print the resulting dictionary
          echo "$dictionary"
        shell: bash

      - name: Use the Dictionary
        run: |
          # You can use the $dictionary variable here, e.g., print a specific value
          echo "Value of 'keyName' is: ${dictionary["keyName"]}"
        shell: bash
