name: Create Dict

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'


jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read JSON and Create Dictionary
        run: |
          # Read the JSON file
          json_content=$(cat rotate_service_account_key/config/cf_config.json)
          
          # Convert the JSON to a dictionary
          dictionary=$(echo $json_content | jq -c 'to_entries | map({key: .key, value: .value}) | from_entries')
          
          # Set the dictionary as an environment variable
          echo "MY_DICTIONARY=$dictionary" >> $GITHUB_ENV

      - name: Use the Dictionary
        run: |
          # Access the dictionary variable
          echo "${MY_DICTIONARY["source"]}"
