name: Create Dict

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'


jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read JSON and Create Dictionary
        run: |
          JSON_CONTENT=$(cat rotate_service_account_key/config/cf_config.json)
          
          declare -A DATA_DICT
          while IFS="=" read -r key value; do
            DATA_DICT["$key"]=$value
          done < <(jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" <<< "$JSON_CONTENT")
          
          echo "Dictionary: ${DATA_DICT}"

        env:
          DATA_DICT: ${{ steps.create-dictionary.outputs.DICTIONARY }}

      - name: Access Dictionary Values
        run: |
          echo ${DATA_DICT["cloud_function_name"]}
