name: Read JSON and Set Variables1

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'
      argument2:
        description: "argument2"
        default: 'some value'

jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read JSON and Set Variables
        run: |
          # Read the JSON file and parse it
          JSON_DATA=$(cat rotate_service_account_key/config/cf_config.json)
          # You can use jq or any other JSON parsing tool here
          # In this example, we'll use jq to extract keys from the JSON file and set them as environment variables
          KEYS=$(echo "$JSON_DATA" | jq -r 'keys[] as $key | "export $key=\(.[$key])"')
          eval "$KEYS"

      - name: Use Environment Variables
        run: |
          echo $name
          echo $age
