name: Read JSON and Set Variables1

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'
      argument2:
        description: "argument2"
        default: 'some value'

jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read JSON and Set Variables
        run: |
          JSON_CONTENT=$(cat rotate_service_account_key/config/cf_config.json)
          for key in $(echo "$JSON_CONTENT" | jq -r 'keys[]'); do
            value=$(echo "$JSON_CONTENT" | jq -r ".$key")
            echo "Setting $key=$value as an environment variable"
            echo "::$key::$value" >> $GITHUB_ENV
          done

      - name: Use Environment Variables
        run: |
          echo "Value of name is $name"
          echo "Value of age is $age"
