name: Create Dict

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'


jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read JSON and Create Dictionary
        run: |
          # Read the JSON file into a variable
          jsonData=$(cat rotate_service_account_key/config/cf_config.json)
          
          # Parse the JSON into a dictionary
          dictionary=$(echo $jsonData | jq -c '.')
          
          echo "Dictionary: $dictionary"

        # This step sets the dictionary as an output for later use
        id: dictionary
        env:
          DICTIONARY: $dictionary
