name: Create Dict

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'
      argument2:
        description: "argument2"
        default: 'some value'

jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Read JSON and Create Dictionary
        run: |
          # Read the JSON file into a variable
          JSON_CONTENT=$(cat rotate_service_account_key/cloud_function)
          
          # Parse the JSON into a dictionary (associative array in Bash)
          declare -A DATA_DICT
          while IFS="=" read -r key value; do
            DATA_DICT["$key"]=$value
          done < <(jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" <<< "$JSON_CONTENT")
          
          # Output the dictionary for reference
          echo "Dictionary: ${DATA_DICT[@]}"
          
          # You can now use the DATA_DICT variable in subsequent steps or jobs.

        env:
          DATA_DICT: ${{ steps.create-dictionary.outputs.DICTIONARY }}