name: Deploy BigQuery

on:
  push:
    branches:
      - dev
    paths:
      - 'rotate_service_account_key/workflow/**'
      - '.github/workflows/rotate_service_account_key_workflow.yml'

    permissions:
      users:
        -  sandesh-sukhadare
        -

jobs:
  super-lint:
    name: rotate_service_account_key workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: contains('[" sandesh-sukhadare ","lpo-ulter"]', github.actor)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/758838218596/locations/global/workloadIdentityPools/id-my-aws-pool-ec2-acc/providers/id-my-aws-pool-ec2-acc
          service_account: rsrt-etl-process-us-acc@rsrt-caspian-us-acc-54cd.iam.gserviceaccount.com
#          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy rotate_service_account_key \
            --gen2 \
            --runtime python310 \
            --region=us-central1 \
            --entry-point main \
            --source rotate_service_account_key/cloud_function \
            --trigger-http \
            --service-account randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com \
            --set-env-vars SA_EMAIL=randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com,SA_NAME=randstad-key-test,secret_id=randstad-secret

      - name: Deploy Workflow
        run: |
          gcloud workflows deploy rotate_service_account_key_wf \
            --source=rotate_service_account_key/workflow/rotate_service_account_key_wf.yml \
            --service-account=randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/758838218596/locations/global/workloadIdentityPools/id-my-aws-pool-ec2-acc/providers/id-my-aws-pool-ec2-acc
          service_account: rsrt-etl-process-us-acc@rsrt-caspian-us-acc-54cd.iam.gserviceaccount.com
#          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy rotate_service_account_key \
            --gen2 \
            --runtime python310 \
            --region=us-central1 \
            --entry-point main \
            --source rotate_service_account_key/cloud_function \
            --trigger-http \
            --service-account ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com \
            --set-env-vars SA_EMAIL=ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com,SA_NAME=ranstad_agri_test,secret_id=randstad-secret 

      - name: Deploy Workflow
        run: |
          gcloud workflows deploy rotate_service_account_key_wf \
            --source=rotate_service_account_key/workflow/rotate_service_account_key_wf.yml \
            --service-account=ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com