name: Rotate Service Account Key WF

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'
      argument2:
        description: "argument2"
        default: 'some value'

    permissions:
      users: # List of GitHub usernames who have access
        -  sandesh-sukhadare
        -


#  push:
#    branches:
#      - main
#    paths:
#      - 'rotate_service_account_key/workflow/**'
#      - '.github/workflows/rotate_service_account_key_workflow.yml'

jobs:
  super-lint:
    name: rotate_service_account_key workflow
    runs-on: ubuntu-latest
    if: contains('[" sandesh-sukhadare ","lpo-ulter"]', github.actor)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3
        with:
          project_id: randstad-etl-poc
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Workflow
        run: |
          gcloud workflows deploy rotate_service_account_key_wf \
            --source=rotate_service_account_key/workflow/rotate_service_account_key_wf.yml \
            --service-account=randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com

