name: Randstad Service Account Key WF

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'
      argument2:
        description: "argument2"
        default: 'some value'

    permissions:
      users: # List of GitHub usernames who have access
        -  sandesh-sukhadare
        -


jobs:
  super-lint:
    name: rotate_service_account_key workflow
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    if: contains('[" sandesh-sukhadare ","lpo-ulter"]', github.actor)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/758838218596/locations/global/workloadIdentityPools/id-my-aws-pool-ec2-acc/providers/id-my-aws-pool-ec2-acc
          service_account: rsrt-etl-process-us-dev@rsrt-caspian-us-dev-a77c.iam.gserviceaccount.com
#          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: 'Use gcloud CLI'
        run: 'gcloud info'


      - name: Deploy Workflow
        run: |
          gcloud workflows deploy rotate_service_account_key_wf \
            --source=rotate_service_account_key/workflow/rotate_service_account_key_wf.yml \
            --service-account=randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com

