name: rotate_service_account_key_workflow

on:
  pull_request:
    types:
      - closed
#  push:
#    paths:
#      - 'rotate_service_account_key/workflow/**'
#      - '.github/workflows/rotate_service_account_key_workflow.yml'

jobs:
  super-lint:
    name: rotate_service_account_key workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is merged to main
        id: pr_merged
        run: |
          if [[ ${{ github.event.pull_request.base.ref }} == "main" && ${{ github.event.pull_request.merged }} == true ]]; then
            echo "::set-output name=merged::true"
          fi
        shell: bash

      - name: Check if changes are within specific folders
        if: steps.pr_merged.outputs.merged == 'true'
        run: |
          affected_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }})
          in_specific_folder=false
          for file in $affected_files; do
            if [[ $file == "path/to/folder1/*" || $file == 'rotate_service_account_key/workflow/**' || $file == '.github/workflows/rotate_service_account_key_workflow.yml' ]]; then
              in_specific_folder=true
              break
            fi
          done
          if [[ $in_specific_folder == true ]]; then
            echo "::set-output name=changes_in_folder::true"
          fi
        shell: bash



      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3
        with:
          project_id: randstad-etl-poc
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Workflow
        if: steps.changes_in_folder.outputs.changes_in_folder == 'true'
        run: |
          gcloud workflows deploy rotate_service_account_key_wf \
            --source=rotate_service_account_key/workflow/rotate_service_account_key_wf.yml \
            --service-account=randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com

