name: Deploy Rotate Service Account Key WF

on:
  workflow_dispatch:
    inputs:
      argument1:
        description: "argument1"
        default: 'some value'
      argument2:
        description: "argument2"
        default: 'some value'

    permissions:
      users: # List of GitHub usernames who have access
        -  sandesh-sukhadare
        -

jobs:
  super-lint:
    name: rotate_service_account_key workflow
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    if: contains('[" sandesh-sukhadare ","lpo-ulter"]', github.actor)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/447510273686/locations/global/workloadIdentityPools/github-actions-cloud-run/providers/github
          service_account: randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com
#          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK P1
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Cloud Function P1
        run: |
          gcloud functions deploy rotate_service_account_key \
            --gen2 \
            --runtime python310 \
            --region=us-central1 \
            --entry-point main \
            --source rotate_service_account_key/cloud_function \
            --trigger-http \
            --service-account randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com \
            --set-env-vars SA_EMAIL=randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com,SA_NAME=randstad-key-test,secret_id=randstad-secret

      - name: Deploy Workflow P1
        run: |
          gcloud workflows deploy rotate_service_account_key_wf \
            --source=rotate_service_account_key/workflow/rotate_service_account_key_wf.yml \
            --service-account=randstad-key-test@randstad-etl-poc.iam.gserviceaccount.com



  super-lint2:
    name: rotate_service_account_key workflow
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    if: contains('[" sandesh-sukhadare ","lpo-ulter"]', github.actor)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/761401601137/locations/global/workloadIdentityPools/github-actions-cloud-run/providers/github
          service_account: ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com
      #          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK P1
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Cloud Function P2
        run: |
          gcloud functions deploy rotate_service_account_key \
            --gen2 \
            --runtime python310 \
            --region=us-central1 \
            --entry-point main \
            --source rotate_service_account_key/cloud_function \
            --trigger-http \
            --service-account ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com \
            --set-env-vars SA_EMAIL=ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com,SA_NAME=ranstad_agri_test,secret_id=randstad-secret

      - name: Deploy Workflow P2
        run: |
          gcloud workflows deploy rotate_service_account_key_wf \
            --source=rotate_service_account_key/workflow/rotate_service_account_key_wf.yml \
            --service-account=ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com







#      - name: Deploy Cloud Function P2
#        run: |
#          gcloud functions deploy rotate_service_account_key \
#            --gen2 \
#            --runtime python310 \
#            --region=us-central1 \
#            --entry-point main \
#            --source rotate_service_account_key/cloud_function \
#            --trigger-http \
#            --service-account ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com \
#            --set-env-vars SA_EMAIL=ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com,SA_NAME=ranstad_agri_test,secret_id=randstad-secret

#      - name: Deploy Workflow P2
#        run: |
#          gcloud workflows deploy rotate_service_account_key_wf \
#            --source=rotate_service_account_key/workflow/rotate_service_account_key_wf.yml \
#            --service-account=ranstad-agri-test@agri-data-analytics.iam.gserviceaccount.com